# Generated by Django 4.2.19 on 2025-02-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote_text', models.CharField()),
                ('is_sent', models.IntegerField(default=0)),
            ],
        ),
    ]
